[audio]
chunk_size = 512
sample_rate = 16000

[render]
width = 512
height = 512
workers = 8
default_fps = 83.28
playback_downsample = 4

[files]
model_dir = 'C:/Users/origa/Desktop/research/usc/span-mri-tools/spanpygui/models'