[audio]
chunk_size = 512
sample_rate = 16000

[render]
width = 512
height = 512
workers = 8
default_fps = 24
format = 'jpeg'
pb_min_fps = 12

[files]
model_dir = 'C:/Users/origa/Desktop/research/usc/span-mri-tools/spanpygui/models'